# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codewatay.com" # the base hostname & protocol for your site

title: لكود وأتاي ( Codewatay )
description: The Voice Of The Moroccan Programming Community
cover: /assets/imgs/cover/cover.jpg

collections:
  episodes:
    output: true

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Build settings
markdown: kramdown
highlighter: null
sass:
    sass_dir: assets/sass

# Handling Reading
exclude: ["README.md"]

# User's info
fullname: متقي الله مدان
fullname_latin: Motaquillah Maddane
email: mailto:codewatay.info@gmail.com
twitter: https://twitter.com/electrik_frog
website: http://electrik-frog.com
facebook: https://www.facebook.com/electrik.frog

# SEO
keywords:
    - podcast
    - programming
    - maroc
    - morocco
    - codewatay
    - لكود وأتاي